# Generated by Django 5.2.3 on 2025-07-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessage',
            new_name='UserMessage',
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'User Message', 'verbose_name_plural': 'Users Messages'},
        ),
    ]
