# Generated by Django 5.2.3 on 2025-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_contactmessage_usermessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_link',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL here', null=True),
        ),
    ]
