# Generated by Django 5.2.3 on 2025-07-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Reselling', 'Reselling'), ('End Use', 'End Use'), ('Raw Material', 'Raw Material')], max_length=100)),
                ('requirement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price inquiry',
                'verbose_name_plural': 'Price inquiries',
            },
        ),
    ]
