# Generated by Django 5.2.3 on 2025-08-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
