# Generated by Django 5.2.3 on 2025-08-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_reviewrating_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='name',
        ),
    ]
