# Generated by Django 5.2.3 on 2025-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_user_alter_cart_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
